In [ ]:
import pandas as pd

# Load the Excel file
df = pd.read_excel("Bezoeken per voertuig 01-01-2025 - 31-01-2025.xlsx")
# View the first 5 rows
print(df.head())

      SerialNumber       Date StartRide     Start      Stop  Distance  \
0  1311 (VPZ-03-J) 2025-01-02  12:31:00  12:38:00  12:40:00       3.2
1  1311 (VPZ-03-J) 2025-01-02  12:40:00  13:00:00  13:01:00      13.5
2  1311 (VPZ-03-J) 2025-01-02  13:01:00  13:01:00  13:36:00       0.1
3  1311 (VPZ-03-J) 2025-01-02  13:36:00  13:56:00  14:16:00      10.7
4  1311 (VPZ-03-J) 2025-01-02  14:16:00  14:33:00  14:40:00      16.0

  TravelTime  Duration                        VisitingAddress Description  \
0   00:06:00  00:01:00  Johan Schippersplantsoen 1, Amsterdam         NaN
1   00:20:00  00:00:00            Schmidtstraat 12, Spaarndam         NaN
2   00:00:00  00:34:00            Schmidtstraat 12, Spaarndam         NaN
3   00:20:00  00:20:00             Schouwtjeslaan 55, Haarlem         NaN
4   00:17:00  00:06:00               Tijnmuiden 75, Amsterdam         NaN

   ...       City ProjectNumber     Break TotalTime TotalTravelTime  \
0  ...  Amsterdam           NaN  00:00:00  00:08:00        00:06:00
1  ...  Spaarndam           NaN  00:00:00  00:29:00        00:27:00
2  ...  Spaarndam           NaN  00:00:00  01:04:00        00:27:00
3  ...    Haarlem           NaN  00:00:00  01:44:00        00:47:00
4  ...  Amsterdam           NaN  00:00:00  02:08:00        01:05:00

  TotalDuration TotalTimeMinusBreak  TotalDistance          Lat        Long
0      00:01:00            00:00:00            3.2  523793823.0  48256393.0
1      00:02:00            00:00:00           16.7  524150138.0  46937561.0
2      00:36:00            00:00:00           16.8  524149597.0   4693831.0
3      00:57:00            00:00:00           27.5  523710894.0  46199301.0
4      01:03:00            00:00:00           43.5  523912751.0  47789565.0

[5 rows x 26 columns]

In [5]:
df['GroupName'].unique()

<StringArray>
[                     '11810500 Amsterdam - ZV',
                     '12030100 Apeldoorn - WMO',
                        '12220100 Arnhem - WMO',
                        '12220700 Arnhem - BBT',
                     '18410 300001 Deventer BT',
                     '19210700 Dordrecht - BBT',
          '22410100 - Goes Klein Frankrijk WMO',
                     '23210100 Groningen - WMO',
                     '23210700 Groningen - BBT',
                       '25310100 Heerlen - WMO',
                       '25810100 Helmond - WMO',
                        '25810300 Helmond - BT',
                       '25810700 Helmond - BBT',
               '25810800 Helmond - Orthototaal',
                        '25820500 Helmond - ZV',
                       '26020100 Hengelo - WMO',
                          '26710700 Goor - BBT',
                        '27220100 Houten - WMO',
                        '32310700 Meppel - BBT',
                         '32320500 Meppel - ZV',
    '32610.100001 - Den Hoorn - Den Haag - WMO',
               '32610.100002 - Den Hoorn - WMO',
               '32610.700001 - Den Hoorn - BBT',
                   '32610300004 Den Hoorn - BT',
           '37010810 Ravenstein - AtlasKidtech',
                           '37610500 Elst - ZV',
                         '37620100013 WMO ELST',
                      '38110300 Purmerend - BT',
                       '41920300 Drachten - BT',
                      '41930100 Drachten - WMO',
                          '44020 600038 Retail',
                       '44040100 Tilburg - WMO',
          '45010104 Utrecht - WMO Advies Pool ',
                        '45010300 Utrecht - BT',
                 '45010516 Utrecht - ZV Advies',
         '45010600 Utrecht - Medipoint winkels',
                       '45010700 Utrecht - BBT',
                         '46130100 Venlo - WMO',
 '48010100 Weesp/Gooi & Vechtstreek/Adam - WMO',
                      '48510100 Maasdijk - WMO',
                       '50120700 Zaandam - BBT',
                         '50130.100 Wormerveer',
                    '51720500 Zwijndrecht - ZV',
            '680 Medipoint Retail Thuisservice',
                           'Poolauto's Utrecht',
                                            nan]
Length: 46, dtype: str

In [6]:
df01 = df[df['GroupName'] == '19210700 Dordrecht - BBT']
df01

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,...,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
16939,967 (VDG-43-S),2025-01-02,06:48:00,07:17:00,10:27:00,35.90,00:28:00,03:10:00,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,00:00:00,03:39:00,00:28:00,03:10:00,00:00:00,35.90,519053952.0,43328348.0
16940,967 (VDG-43-S),2025-01-02,10:27:00,10:39:00,10:43:00,5.10,00:11:00,00:03:00,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,00:00:00,03:54:00,00:40:00,03:14:00,00:00:00,41.00,519053952.0,43328348.0
16941,967 (VDG-43-S),2025-01-02,10:43:00,11:36:00,12:17:00,61.00,00:53:00,00:41:00,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,00:00:00,05:29:00,01:33:00,03:55:00,00:00:00,102.00,519053952.0,43328348.0
16942,967 (VDG-43-S),2025-01-02,12:17:00,12:58:00,14:51:00,27.30,00:40:00,01:52:00,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,00:00:00,08:02:00,02:14:00,05:47:00,00:00:00,129.30,519053952.0,43328348.0
16943,967 (VDG-43-S),2025-01-02,14:51:00,15:06:00,06:55:00,3.70,00:15:00,15:49:00,"Produktiestraat 2, Vlaardingen",NaN,...,Vlaardingen,NaN,00:00:00,08:17:00,02:29:00,05:47:00,08:17:00,133.00,519053952.0,43328348.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21738,1775 (V-11-GGL),2025-01-31,07:35:00,07:41:00,08:05:00,1.37,00:05:00,00:24:00,"Groen Van Prinstererweg 38, Dordrecht",NaN,...,Dordrecht,NaN,00:00:00,02:22:00,00:49:00,01:33:00,00:00:00,42.95,51791194.0,46664807.0
21739,1775 (V-11-GGL),2025-01-31,08:05:00,08:12:00,08:28:00,2.02,00:06:00,00:16:00,"Albert Schweitzerplaats 1, Dordrecht",NaN,...,Dordrecht,NaN,00:00:00,02:45:00,00:55:00,01:50:00,00:00:00,44.97,51792834.0,46826266.0
21740,1775 (V-11-GGL),2025-01-31,08:28:00,08:35:00,08:45:00,3.44,00:06:00,00:09:00,"Bankastraat 158, Dordrecht",NaN,...,Dordrecht,NaN,00:00:00,03:02:00,01:02:00,01:59:00,00:00:00,48.41,518080094.0,46862529.0
21741,1775 (V-11-GGL),2025-01-31,08:45:00,09:06:00,09:18:00,13.52,00:21:00,00:11:00,"Ijsvogelplein 33, Zwijndrecht",NaN,...,Zwijndrecht,NaN,00:00:00,03:35:00,01:24:00,02:11:00,00:00:00,61.93,518124186.0,46221905.0
21742,1775 (V-11-GGL),2025-01-31,09:18:00,09:23:00,09:40:00,2.28,00:04:00,00:16:00,"Plantageweg 3, Zwijndrecht",NaN,...,Zwijndrecht,NaN,00:00:00,03:57:00,01:29:00,02:28:00,03:57:00,64.21,518153146.0,46308245.0

In [7]:
df01.columns

Index(['SerialNumber', 'Date', 'StartRide', 'Start', 'Stop', 'Distance',
       'TravelTime', 'Duration', 'VisitingAddress', 'Description',
       'DriverName', 'GroupName', 'Contact', 'Remark', 'To', 'ZipCode', 'City',
       'ProjectNumber', 'Break', 'TotalTime', 'TotalTravelTime',
       'TotalDuration', 'TotalTimeMinusBreak', 'TotalDistance', 'Lat', 'Long'],
      dtype='str')

In [8]:
df01['DriverName'].unique()

<StringArray>
[                        nan,         'Aart van der Wulp',
 'Auto Mertens Auto Mertens',           'Tom Barendrecht',
           'Tjerk Polderman',            'Sandro Glasius',
              'Liza de Gier',                'Ronald Kok',
            'Marcel Koevoet',  'Cornelis van der Giessen',
     'Geertjan van der Wulp',              'Roy Albersen',
              'Robin Kovács',               'Kees Kuiper',
                'Peter Bood',           'Joost Oerlemans',
             'Onno Havelaar',           'Enzo van Dongen',
                'Erik-Jan 3',             'Bas van Steen',
                'Ron Timmer',       'Peter van den Bosch',
             'Hans de Groot',              'Frido Wijnen',
            'Sheamie Gerard',            'Frans Boshoven',
       'René Hoppenbrouwers',            'Barend de Jong',
             'Ronald Griend',             'Marcus Dekker',
               'Alin Apetri',      'Joost van der Linden']
Length: 32, dtype: str

In [9]:
df02 = df01[df01['DriverName'] == 'Joost Oerlemans']
df02

,SerialNumber,Date,StartRide,Start,Stop,Distance,TravelTime,Duration,VisitingAddress,Description,...,City,ProjectNumber,Break,TotalTime,TotalTravelTime,TotalDuration,TotalTimeMinusBreak,TotalDistance,Lat,Long
18549,1319 (VPS-08-J),2025-01-02,08:52:00,09:23:00,10:09:00,26.85,00:30:00,00:45:00,"Gouvernestraat 88, Rotterdam",NaN,...,Rotterdam,NaN,00:00:00,02:41:00,00:39:00,02:02:00,00:00:00,26.86,519178046.0,44701145.0
18550,1319 (VPS-08-J),2025-01-02,10:09:00,10:27:00,10:35:00,1.72,00:18:00,00:08:00,"Schimmelpenninckstraat 144, Rotterdam",NaN,...,Rotterdam,NaN,00:00:00,03:07:00,00:57:00,02:10:00,00:00:00,28.58,519250756.0,44602088.0
18551,1319 (VPS-08-J),2025-01-02,10:35:00,10:45:00,10:53:00,3.24,00:10:00,00:07:00,"Kleiweg 500, Rotterdam",NaN,...,Rotterdam,NaN,00:00:00,03:25:00,01:07:00,02:17:00,00:00:00,31.82,519406675.0,44623538.0
18552,1319 (VPS-08-J),2025-01-02,10:53:00,11:06:00,11:11:00,5.24,00:13:00,00:04:00,"Van Beethovenlaan 121, Rotterdam",NaN,...,Rotterdam,NaN,00:00:00,03:43:00,01:20:00,02:22:00,00:00:00,37.06,5195621.0,45120495.0
18553,1319 (VPS-08-J),2025-01-02,11:11:00,11:35:00,11:44:00,8.14,00:24:00,00:08:00,"'S-Gravenweg 355, Capelle Aan Den Ijssel",NaN,...,Capelle Aan Den Ijssel,NaN,00:00:00,04:16:00,01:45:00,02:31:00,00:00:00,45.20,519440835.0,45988378.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18821,1319 (VPS-08-J),2025-01-31,10:53:00,10:58:00,11:09:00,1.13,00:05:00,00:10:00,"Ridder Van Catsweg 258, Gouda",NaN,...,Gouda,NaN,00:00:00,05:09:00,03:01:00,02:07:00,00:00:00,132.18,520270668.0,47079483.0
18822,1319 (VPS-08-J),2025-01-31,11:09:00,11:35:00,11:59:00,16.43,00:26:00,00:24:00,"Prins Bernhardstraat 57, Oudewater",NaN,...,Oudewater,NaN,00:00:00,05:59:00,03:27:00,02:32:00,00:00:00,148.61,520286015.0,48686296.0
18823,1319 (VPS-08-J),2025-01-31,11:59:00,12:18:00,12:21:00,19.38,00:18:00,00:03:00,"Veldhuizerweg 2, Harmelen",NaN,...,Harmelen,NaN,00:00:00,06:21:00,03:45:00,02:35:00,00:00:00,167.99,520821231.0,50030913.0
18824,1319 (VPS-08-J),2025-01-31,12:21:00,12:30:00,12:46:00,4.05,00:08:00,00:16:00,"Alenveltpark 1 , Vleuten",De Rijnhoven - Zorgcentrum Parkhof,...,Vleuten,0.0,00:00:00,06:46:00,03:54:00,02:51:00,00:00:00,172.04,521047225.0,50158771.0
18825,1319 (VPS-08-J),2025-01-31,12:46:00,13:22:00,13:27:00,39.20,00:35:00,00:05:00,"Europalaan 2, Nieuwerkerk Ad Ijssel",NaN,...,Nieuwerkerk Ad Ijssel,NaN,00:00:00,07:27:00,04:30:00,02:57:00,07:27:00,211.24,519676483.0,45995676.0